language: python
python:
  - "2.7"
  - "3.4"
cache:
  directories:
    - /home/travis/virtualenv/python2.7/lib/python2.7/site-packages
    - /home/travis/virtualenv/python3.4/lib/python3.4/site-packages
install:
  - pip install -r requirements.txt
  - 2to3 --write --nobackup hocr-*
  - python setup.py install
  # - pip install pep8
script: 
  - ./test/tsht
  # - pep8 hocr-* setup.py; true
